world_name: "empty"
origin: 
    latitude: 40.337494
    longitude: -3.883197
    altitude: 100.0
drones:
  - model_type: "crazyflie_led_ring"
    model_name: "drone0"
    flight_time: 60
    xyz:
      - -1.0
      - 0.0
      - 0.2
  - model_type: "crazyflie_led_ring"
    model_name: "drone1"
    flight_time: 60
    xyz:
      - 1.0
      - 0.0
      - 0.2
  - model_type: "crazyflie_led_ring"
    model_name: "drone2"
    flight_time: 60
    xyz:
      - 0.0
      - 0.0
      - 0.2
  - model_type: "crazyflie_led_ring"
    model_name: "drone3"
    flight_time: 60
    xyz:
      - 0.0
      - 1.0
      - 0.2
  - model_type: "crazyflie_led_ring"
    model_name: "drone4"
    flight_time: 60
    xyz:
      - 0.0
      - -1.0
      - 0.2

